//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodeSalesApp.App.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BarcodeSalesApp.App.Resources.Strings.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Language.
        /// </summary>
        public static string ActiveLang {
            get {
                return ResourceManager.GetString("ActiveLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product.
        /// </summary>
        public static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        public static string Barcode {
            get {
                return ResourceManager.GetString("Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box Count.
        /// </summary>
        public static string BoxCount {
            get {
                return ResourceManager.GetString("BoxCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart is empty.
        /// </summary>
        public static string CartIsEmpty {
            get {
                return ResourceManager.GetString("CartIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Shortcut.
        /// </summary>
        public static string ClearShortcutKey {
            get {
                return ResourceManager.GetString("ClearShortcutKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Sale.
        /// </summary>
        public static string CompleteSale {
            get {
                return ResourceManager.GetString("CompleteSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Shortcut:.
        /// </summary>
        public static string CurrentClearShortcut {
            get {
                return ResourceManager.GetString("CurrentClearShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Shortcut:.
        /// </summary>
        public static string CurrentSaleShortcut {
            get {
                return ResourceManager.GetString("CurrentSaleShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Mode.
        /// </summary>
        public static string DayMode {
            get {
                return ResourceManager.GetString("DayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete product?.
        /// </summary>
        public static string DeleteProductConfirmText {
            get {
                return ResourceManager.GetString("DeleteProductConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the deletion process.
        /// </summary>
        public static string DeleteProductError {
            get {
                return ResourceManager.GetString("DeleteProductError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product successfully deleted!.
        /// </summary>
        public static string DeleteProductSuccess {
            get {
                return ResourceManager.GetString("DeleteProductSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Product: {0}.
        /// </summary>
        public static string DeleteProductTitle {
            get {
                return ResourceManager.GetString("DeleteProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Shortcuts.
        /// </summary>
        public static string EditShortcuts {
            get {
                return ResourceManager.GetString("EditShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Of Day Report.
        /// </summary>
        public static string EndOfDayReport {
            get {
                return ResourceManager.GetString("EndOfDayReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Stock.
        /// </summary>
        public static string EnterStock {
            get {
                return ResourceManager.GetString("EnterStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming Box Amount.
        /// </summary>
        public static string IncomingBoxAmount {
            get {
                return ResourceManager.GetString("IncomingBoxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Barcoded.
        /// </summary>
        public static string IsBarcoded {
            get {
                return ResourceManager.GetString("IsBarcoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Product Added!.
        /// </summary>
        public static string NewProduct {
            get {
                return ResourceManager.GetString("NewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        public static string NightMode {
            get {
                return ResourceManager.GetString("NightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Shortcut for Clear Operation Found!.
        /// </summary>
        public static string NoClearShortcut {
            get {
                return ResourceManager.GetString("NoClearShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Sales Found.
        /// </summary>
        public static string NoSalesFound {
            get {
                return ResourceManager.GetString("NoSalesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Shortcut for Sale Operation Found!.
        /// </summary>
        public static string NoSaleShortcut {
            get {
                return ResourceManager.GetString("NoSaleShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Detail.
        /// </summary>
        public static string ProductDetail {
            get {
                return ResourceManager.GetString("ProductDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product registered with this barcode ({0}) is: {1}.
        /// </summary>
        public static string ProductExists {
            get {
                return ResourceManager.GetString("ProductExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items per Box.
        /// </summary>
        public static string ProductInBox {
            get {
                return ResourceManager.GetString("ProductInBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Information.
        /// </summary>
        public static string ProductInfo {
            get {
                return ResourceManager.GetString("ProductInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product List.
        /// </summary>
        public static string ProductList {
            get {
                return ResourceManager.GetString("ProductList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Not Found.
        /// </summary>
        public static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Updated!.
        /// </summary>
        public static string ProductUpdated {
            get {
                return ResourceManager.GetString("ProductUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit.
        /// </summary>
        public static string Profit {
            get {
                return ResourceManager.GetString("Profit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Price.
        /// </summary>
        public static string PurchasePrice {
            get {
                return ResourceManager.GetString("PurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Sold.
        /// </summary>
        public static string QuantitySold {
            get {
                return ResourceManager.GetString("QuantitySold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Default.
        /// </summary>
        public static string ResetKeys {
            get {
                return ResourceManager.GetString("ResetKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear the shortcuts?.
        /// </summary>
        public static string ResetShortcutConfirmText {
            get {
                return ResourceManager.GetString("ResetShortcutConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the reset process.
        /// </summary>
        public static string ResetShortcutError {
            get {
                return ResourceManager.GetString("ResetShortcutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts successfully reset!.
        /// </summary>
        public static string ResetShortcutSuccess {
            get {
                return ResourceManager.GetString("ResetShortcutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Shortcuts.
        /// </summary>
        public static string ResetShortcutTitle {
            get {
                return ResourceManager.GetString("ResetShortcutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Stock.
        /// </summary>
        public static string ResetStock {
            get {
                return ResourceManager.GetString("ResetStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset this product&apos;s stock?.
        /// </summary>
        public static string ResetStockConfirmText {
            get {
                return ResourceManager.GetString("ResetStockConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the reset process.
        /// </summary>
        public static string ResetStockError {
            get {
                return ResourceManager.GetString("ResetStockError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock successfully reset!.
        /// </summary>
        public static string ResetStockSuccess {
            get {
                return ResourceManager.GetString("ResetStockSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Stock.
        /// </summary>
        public static string ResetStockTitle {
            get {
                return ResourceManager.GetString("ResetStockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows Per Page.
        /// </summary>
        public static string RowsPerPage {
            get {
                return ResourceManager.GetString("RowsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Amount.
        /// </summary>
        public static string SaleAmount {
            get {
                return ResourceManager.GetString("SaleAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Failed.
        /// </summary>
        public static string SaleFailed {
            get {
                return ResourceManager.GetString("SaleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Price.
        /// </summary>
        public static string SalePrice {
            get {
                return ResourceManager.GetString("SalePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        public static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Shortcut Key.
        /// </summary>
        public static string SaleShortcutKey {
            get {
                return ResourceManager.GetString("SaleShortcutKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales List.
        /// </summary>
        public static string SalesList {
            get {
                return ResourceManager.GetString("SalesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Page.
        /// </summary>
        public static string SalesPage {
            get {
                return ResourceManager.GetString("SalesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Records.
        /// </summary>
        public static string SalesRecords {
            get {
                return ResourceManager.GetString("SalesRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Barcode:.
        /// </summary>
        public static string ScanBarcode {
            get {
                return ResourceManager.GetString("ScanBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Date.
        /// </summary>
        public static string SelectDate {
            get {
                return ResourceManager.GetString("SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By.
        /// </summary>
        public static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Information.
        /// </summary>
        public static string StockInfo {
            get {
                return ResourceManager.GetString("StockInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units per Box.
        /// </summary>
        public static string StockMultiplier {
            get {
                return ResourceManager.GetString("StockMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Unit.
        /// </summary>
        public static string StockUnit {
            get {
                return ResourceManager.GetString("StockUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Unit Count.
        /// </summary>
        public static string StockUnitCount {
            get {
                return ResourceManager.GetString("StockUnitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Update.
        /// </summary>
        public static string StockUpdate {
            get {
                return ResourceManager.GetString("StockUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode Sales.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Profit.
        /// </summary>
        public static string TotalProfit {
            get {
                return ResourceManager.GetString("TotalProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Sales.
        /// </summary>
        public static string TotalSales {
            get {
                return ResourceManager.GetString("TotalSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Stock.
        /// </summary>
        public static string TotalStock {
            get {
                return ResourceManager.GetString("TotalStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Stock Quantity.
        /// </summary>
        public static string TotalStockQuantity {
            get {
                return ResourceManager.GetString("TotalStockQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        public static string Turkish {
            get {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units Per Case.
        /// </summary>
        public static string UnitsPerCase {
            get {
                return ResourceManager.GetString("UnitsPerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Product.
        /// </summary>
        public static string UpdateProduct {
            get {
                return ResourceManager.GetString("UpdateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts Updated!.
        /// </summary>
        public static string UpdateShortcutSuccess {
            get {
                return ResourceManager.GetString("UpdateShortcutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Updated!.
        /// </summary>
        public static string UpdateStockSuccess {
            get {
                return ResourceManager.GetString("UpdateStockSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        public static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
